#!/usr/bin/env bash

if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi

# install docker
install_docker()
{
	# https://docs.docker.com/engine/installation/linux/ubuntulinux/
	curl -sSL get.docker.com | sh
	docker --version
	systemctl enable docker
	systemctl start docker
	usermod -aG docker "$(who -m | awk '{print $1;}')"
}

install_pip()
{
	curl --silent --show-error --retry 5 https://bootstrap.pypa.io/get-pip.py | python2.7
}

install_virtualenv()
{
	install_pip
	pip install --upgrade virtualenv virtualenvwrapper
	rm -rf ~/.cache/pip
	export WORKON_HOME="/home/$(who -m | awk '{print $1;}')/.virtualenvs"
	mkdir -p "$WORKON_HOME" || true
	source /usr/local/bin/virtualenvwrapper.sh
}

# install docker-compose
install_compose()
{
	install_virtualenv
	mkvirtualenv docker-compose -p python2
	pip install --upgrade docker-compose
	ln -sf "$(which docker-compose)" /usr/local/bin/docker-compose
	deactivate
	docker-compose --version
}

# includes ts utility for timestamping logs
install_moreutils()
{
	apt-get install "moreutils" -y
}

install_all()
{
	install_docker
	install_compose
	install_moreutils
}

usage()
{
	echo "usage: $(basename "${0}") [options]"
	echo "options:"
	compgen -A function | sed -nr 's|^install_(.+)$|  \1|p'
	exit 1
}

[ -n "$1" ] || usage
for util in $@
do
	eval "install_${util}" || usage
done
