#!/usr/bin/env bash

if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi

# install docker
install_docker()
{
	# https://docs.docker.com/engine/installation/linux/ubuntulinux/
	curl -sSL get.docker.com | sh
	docker --version
	systemctl enable docker
	systemctl start docker
	usermod -aG docker "$(who -m | awk '{print $1;}')"
}

# install docker-compose
install_compose()
{
	apt install -y python-pip
	pip install --upgrade pip
	pip install --upgrade docker-compose
	docker-compose --version
}

# includes ts utility for timestamping logs
install_moreutils()
{
	apt-get install "moreutils" -y
}

install_all()
{
	install_docker
	install_compose
	install_moreutils
}

usage()
{
	echo "usage: $(basename "${0}") [options]"
	echo "options:"
	compgen -A function | sed -nr 's|^install_(.+)$|  \1|p'
	exit 1
}

[ -n "$1" ] || usage
for util in $@
do
	eval "install_${util}" || usage
done
