#!/usr/bin/env bash

if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi

compose_bin="$(which docker-compose | head -n1)" 
if [ ! -x "$compose_bin" ] 
then
	echo "docker-compose not found, please run install script" 1>&2
	exit 1
else
	"$compose_bin" --version
fi

abs_root() { echo "$(cd "$(dirname "${1}")" && pwd)"; }
project_root="$(abs_root "$(abs_root "$0")")"

# source environment variables required for containers
. "$project_root/compose.env"

# run container
"$compose_bin" -f "$project_root/docker-compose.yml" run --rm "$1"
